AT_func_todolist/MVC_todolist/Models/ErrorViewModel.cs
using System;

namespace MVC_todolist.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AT_func_todolist/MVC_todolist/Models/EventosModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_todolist.Models
{
    /*public class EventosModel
    {
        public IEnumerable<Models.ListaModel> EventosHoje { get; set; }

        public IEnumerable<Models.ListaModel> EventosProximos { get; set; }
    }
    */
}

AT_func_todolist/MVC_todolist/Models/ListaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_todolist.Models
{
    public class ListaModel
    {
        
        public Guid Id { get; set; }

        
        public string NomeTarefa { get; set; }

        
        public DateTime DataTarefa { get; set; }

        
        public string Detalhes { get; set; }

        
        public string Status { get; set; }

        
        public string Responsavel { get; set; }

  
    }
}

AT_func_todolist/MVC_todolist/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_todolist.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_todolist.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AT_func_todolist/MVC_todolist/Controllers/todolistController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC_todolist.Infra;
using MVC_todolist.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_todolist.Controllers
{
    public class todolistController : Controller
    {
        private readonly ListaRest agendaRest;

        public todolistController()
        {
            this.agendaRest = new ListaRest();
        }
        // GET: todolistController
        public ActionResult Index()
        {
            var model = this.agendaRest.GetAll();
            return View(model);
        }

        // GET: todolistController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = this.agendaRest.GetById(id);

            return View(model);
        }

        // GET: todolistController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: todolistController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ListaModel model)
        {
            try
            {
                this.agendaRest.Save(model);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: todolistController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = this.agendaRest.GetById(id);
            return View(model);
           
        }

        // POST: todolistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, ListaModel model)
        {
            try
            {
                model.Id = id;
                this.agendaRest.Update(model);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: todolistController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = this.agendaRest.GetById(id);
            return View(model);


            
        }

        // POST: todolistController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, ListaModel model)
        {

            this.agendaRest.Delete(id);


            return RedirectToAction(nameof(Index));


        }
    }
}

AT_func_todolist/MVC_todolist/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">AT - To do List</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<!--<div class="align-content-lg-between">
    <div class="text-center">
        <p>tarefas de Hoje</p>
        <p>##</p>
        <table class="table">
            //*foreach (var item in Model.Aniversariantes)
            {
                <tr>
                    <td>
                        Html.DisplayNameFor(model => model.NomeTarefa)
                    </td>
                    <td>
                        Html.DisplayFor(modelItem => item.DataTarefa)
                    </td>
                    <td>
                        Html.DisplayFor(modelItem => item.Responsavel)
                    </td>

                </tr>
            }
        </table>
        <hr />
        <table class="table">
            foreach (var item in Model.ProximosAniversariantes)
            {
                <tr>
                    <td>
                        Html.DisplayNameFor(model => model.NomeTarefa)
                    </td>
                    <td>
                        Html.DisplayFor(modelItem => item.DataTarefa)
                    </td>
                    <td>
                        Html.DisplayFor(modelItem => item.Responsavel)
                    </td>

                </tr>
            }
        </table>

    </div>
</div>
    -->

AT_func_todolist/MVC_todolist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_todolist</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style scoped>
        
        a {
            list-style: none;
            transition: 0.3s opacity;
            text-decoration: none;
        }

            a:hover {
                opacity: 0.7;
                color: #000000;
                text-decoration: none;
            }

        .buttonAdd {
            border: 3px solid #04AA6D;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

        .buttonErase {
            border: 3px solid #ff5050;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

        .buttonEdit {
            border: 3px solid #ffd452;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }

        .buttonInfo {
            border: 3px solid #52d4ff;
            padding: 7px 7px;
            text-align: center;
            text-decoration: none;
            color: black;
            display: inline-block;
            font-size: 14px;
            margin: 4px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_todolist</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="todolist" asp-action="Index">Lista de tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TP1 - Feito por Eric F Guimarães - <a href="https://linkedin.com/in/ericfguimaraes"><img src="~/Assets/Img/linkedin.svg" class="img" width="20" alt="Linkedin" /></a> |
            <a href="https://github.com/ericfg19/"><img src="~/Assets/Img/github.svg" class="img" width="22" alt="GitHub" /></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AT_func_todolist/MVC_todolist/Views/todolist/Create.cshtml
@model MVC_todolist.Models.ListaModel

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Tarefa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                Nome da tarefa
                <input asp-for="NomeTarefa" class="form-control" required/>
                <span asp-validation-for="NomeTarefa" class="text-danger"></span>
            </div>
            <div class="form-group">
                Data da tarefa
                <input asp-for="DataTarefa" class="form-control" />
                <span asp-validation-for="DataTarefa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalhes" class="control-label"></label>
                <input asp-for="Detalhes" class="form-control" />
                <span asp-validation-for="Detalhes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" required/>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                Responsável
                <input asp-for="Responsavel" class="form-control" required/>
                <span asp-validation-for="Responsavel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" /> <img src="~/Assets/Img/check-circle-fill.svg" class="img" fill="currentColor" alt="Adicionar Tarefa" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AT_func_todolist/MVC_todolist/Views/todolist/Delete.cshtml
@model MVC_todolist.Models.ListaModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>


<div>
    <h4>Informações da tarefa:</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeTarefa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeTarefa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataTarefa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataTarefa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Detalhes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detalhes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Responsavel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Responsavel)
        </dd>
    </dl>
    <h3>Tem certeza que irá deletar a tarefa?</h3>
    <form asp-action="Delete">
        <input type="submit" value="Deletar" class="btn btn-danger"/> |
        <a asp-action="Index">Não, voltar para a lista</a>
    </form>
</div>

AT_func_todolist/MVC_todolist/Views/todolist/Details.cshtml
@model MVC_todolist.Models.ListaModel

@{
    ViewData["Title"] = "detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Informações da tarefa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            Nome da tarefa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeTarefa)
        </dd>
        <dt class = "col-sm-2">
            Data
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataTarefa)
        </dd>
        <dt class = "col-sm-2">
            Detalhes
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detalhes)
        </dd>
        <dt class = "col-sm-2">
            Status
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            Responsável
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Responsavel)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit") <img src="~/Assets/Img/pencil.svg" class="img" fill="currentColor" alt="Editar" /> |
    <a asp-action="Index">Voltar para a lista</a>
</div>

AT_func_todolist/MVC_todolist/Views/todolist/Edit.cshtml
@model MVC_todolist.Models.ListaModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar/Atualizar</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                Nome da tarefa
                <input asp-for="NomeTarefa" class="form-control" />
                <span asp-validation-for="NomeTarefa" class="text-danger"></span>
            </div>
            <div class="form-group">
                Data
                <input asp-for="DataTarefa" class="form-control" />
                <span asp-validation-for="DataTarefa" class="text-danger"></span>
            </div>
            <div class="form-group">
                Detalhes
                <input asp-for="Detalhes" class="form-control" />
                <span asp-validation-for="Detalhes" class="text-danger"></span>
            </div>
            <div class="form-group">
                Status
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                Responsável
                <input asp-for="Responsavel" class="form-control" />
                <span asp-validation-for="Responsavel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" /> <img src="~/Assets/Img/check-circle-fill.svg" class="img" fill="currentColor" alt="Adicionar Tarefa" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AT_func_todolist/MVC_todolist/Views/todolist/Index.cshtml
@model IEnumerable<MVC_todolist.Models.ListaModel>

@{
    ViewData["Title"] = "Tarefas";
}

<h1>Agendamento de Tarefas</h1>

<p>
    <a asp-action="Create">Criar nova tarefa</a>
</p>
<div class="col-4 p-0 justify-content-end">
    <form asp-controller="Agenda" asp-action="Index">
        <input class="btn-group" type="text" name="tarefa" />
        <span type="text" placeholder="Nome da Tarefa">
            <input class="btn-sm btn-info" type="submit" value="Filtrar" />
        </span>

    </form>
    <div>
        <a asp-action="Index">Limpar Filtro</a>
    </div>

</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Tarefa
            </th>
            <th>
                Data
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                Responsável
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeTarefa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataTarefa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Responsavel)
            </td>
            <td>
                   @Html.ActionLink("Editar", "Edit", new { id=item.Id }) <img src="~/Assets/Img/pencil.svg" class="img" fill="currentColor" alt="Editar" /> |
                   @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) <img src="~/Assets/Img/info-circle.svg" class="img" fill="currentColor" alt="Detalhes" /> |
                   @Html.ActionLink("Deletar", "Delete", new { id = item.Id }) <img src="~/Assets/Img/eraser-fill.svg" class="img" fill="currentColor" alt="Deletar" />
            </td>
        </tr>
}
    </tbody>
</table>